In [ ]:
import matplotlib.pyplot as plt
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x, y)

LogisticRegression()

In [ ]:
print(model.intercept_, model.coef_)

[-4.12617727] [[1.18109091]]


In [ ]:
model.predict_proba(x)

array([[0.98411203, 0.01588797],
       [0.95003074, 0.04996926],
       [0.85370936, 0.14629064],
       [0.64173546, 0.35826454],
       [0.35475873, 0.64524127],
       [0.1443924 , 0.8556076 ],
       [0.04924876, 0.95075124],
       [0.01565079, 0.98434921],
       [0.00485659, 0.99514341],
       [0.00149573, 0.99850427]])

In [ ]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
model.predict(x)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
model.score(x, y)

1.0

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('bankloan.csv')

In [ ]:
df.head()

age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0   41   3      17       12     176      9.3  11.359392  5.008608        1
1   27   1      10        6      31     17.3   1.362202  4.000798        0
2   40   1      15       14      55      5.5   0.856075  2.168925        0
3   41   1      15       14     120      2.9   2.658720  0.821280        0
4   24   2       2        0      28     17.3   1.787436  3.056564        1

In [ ]:
X = df[['employ','debtinc', 'creddebt', 'othdebt']]
y = df['default']

In [ ]:
X

employ  debtinc   creddebt   othdebt
0        17      9.3  11.359392  5.008608
1        10     17.3   1.362202  4.000798
2        15      5.5   0.856075  2.168925
3        15      2.9   2.658720  0.821280
4         2     17.3   1.787436  3.056564
..      ...      ...        ...       ...
695       6      4.6   0.262062  0.979938
696       6     11.5   0.369495  2.045505
697      15      7.6   0.491264  1.940736
698      19      8.4   2.302608  4.165392
699      12     14.7   2.994684  3.473316

[700 rows x 4 columns]

In [ ]:
y

0      1
1      0
2      0
3      0
4      1
      ..
695    1
696    0
697    0
698    0
699    0
Name: default, Length: 700, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
X_train

employ  debtinc  creddebt   othdebt
558       2      2.5  0.199325  0.225675
404      18     15.4  2.099636  3.136364
505       2     19.9  1.522350  4.447650
342      15      4.9  0.421792  1.146208
417       4      4.6  0.053360  1.280640
..      ...      ...       ...       ...
551       0      9.0  0.781200  2.368800
294      10      9.8  3.236548  1.565452
396      14     17.0  1.137640  3.622360
369      22      2.3  0.826551  1.450449
388       7      4.9  0.225400  0.901600

[560 rows x 4 columns]

In [ ]:
X_test

employ  debtinc   creddebt    othdebt
86        5     12.4   3.490848   0.973152
155      13     19.2   2.800512   4.687488
309       4     10.1   1.060500   1.464500
116       9      6.2   2.107690   1.922310
267       9     14.6   3.109654   5.504346
..      ...      ...        ...        ...
430      12     25.1   7.817144   9.250856
387      15      3.1   0.476532   3.429468
75       13     23.8   3.738504   8.399496
432       9      6.6   0.789888   3.434112
632      31     23.1  14.231448  17.184552

[140 rows x 4 columns]

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
model.score(X_test, y_test)

0.8785714285714286

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
model.score(X_test, y_test)

0.7928571428571428

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
naive = GaussianNB()
naive.fit(X_train, y_train)
naive.score(X_test, y_test)

0.8285714285714286

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.6857142857142857