#Soal Nomor 1

In [ ]:
import numpy as np

#input
start = int(input('Mulai : '))
end = int(input('Selesai : '))

Mulai : 1
Selesai : 28


In [ ]:
#1 Dimensi
arr = np.arange(start, end)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [ ]:
# 2 Dimensi

if len(arr) %2 == 1:
  column = int(len(arr)**(1/3))
  row = int(column**2)
else:
  column = int(len(arr)**(1/2))
  row = column

arr2 = arr.reshape(column, row)
print(arr2)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


In [ ]:
#3 Dimensi
arr3 = arr2.reshape(column, column, column)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


#Soal Nomor 2

In [ ]:
import random

#input
length = int(input('Banyak Data : '))
start = int(input('Mulai : '))
end = int(input('Selesai : '))


Banyak Data : 16
Mulai : 1
Selesai : 50


In [ ]:
#bangkitkan array 1 dimensi dari random integer
arr = []

for i in range(length):
  arr.append(random.randint(start, end))

print(arr)

[5, 26, 47, 20, 48, 42, 27, 6, 31, 23, 31, 4, 28, 17, 29, 31]


In [ ]:
# 2 Dimensi
import numpy as np

if len(arr) %2 == 1:
  column = int(len(arr)**(1/3))
  row = int(column**2)
else:
  column = int(len(arr)**(1/2))
  row = column

numpy_arr = np.array(arr)
arr2 = numpy_arr.reshape(column, row)
print(arr2)

[[ 5 26 47 20]
 [48 42 27  6]
 [31 23 31  4]
 [28 17 29 31]]


In [ ]:
arr_reverse = []
for i in arr2:
  arr_reverse.append(i[::-1])
print(np.array(arr_reverse))

[[20 47 26  5]
 [ 6 27 42 48]
 [ 4 31 23 31]
 [31 29 17 28]]


In [ ]:
import numpy as np
arr2 = []
for i in range (0,10):
  arr = []
  if i == 0 or i == 9:
    for i in range (0,10):
      arr.append(4.)
  else:
    for i in range (0,10):
      if i == 0 or i == 9:
        arr.append(4.)
      else:
        arr.append(0.)
  arr2.append(arr)

print(arr2)

[10]
